services:
  mcp:
    build: .
    container_name: mcp-server
    expose:
      - "8000"
    networks:
      - mcp-network

  nginx:
    image: nginx:latest
    container_name: mcp-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mcp
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
